// Ce fichier est une partie de KeepLink PRO
// Copyright (c)2005 Tech&Feel (aurelien.boudoux@techandfeel.net)

#if !defined(AFX_IZSSMSX_H__92CF5024_C066_46A1_8211_2E5FF3EBF5CD__INCLUDED_)
#define AFX_IZSSMSX_H__92CF5024_C066_46A1_8211_2E5FF3EBF5CD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CIzsSmsX wrapper class

class CIzsSmsX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CIzsSmsX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xacbf5346, 0xfd5b, 0x4dc4, { 0xb0, 0x81, 0xab, 0xe0, 0x78, 0x3a, 0xf6, 0x63 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void Send();
	CString GetAbout();
	void SetAbout(LPCTSTR lpszNewValue);
	CString GetComLibVersion();
	void SetComLibVersion(LPCTSTR lpszNewValue);
	long GetBaud();
	void SetBaud(long nNewValue);
	CString GetPort();
	void SetPort(LPCTSTR lpszNewValue);
	CString GetPrefixString();
	void SetPrefixString(LPCTSTR lpszNewValue);
	CString GetInitString();
	void SetInitString(LPCTSTR lpszNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CString GetSendTo();
	void SetSendTo(LPCTSTR lpszNewValue);
	long GetState();
	void StepIt();
	void StepBy(long Delta);
	short GetDragCursor();
	void SetDragCursor(short nNewValue);
	long GetDragMode();
	void SetDragMode(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	long GetMin();
	void SetMin(long nNewValue);
	long GetMax();
	void SetMax(long nNewValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	long GetPosition();
	void SetPosition(long nNewValue);
	BOOL GetSmooth();
	void SetSmooth(BOOL bNewValue);
	long GetStep();
	void SetStep(long nNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	void FlipChildren(BOOL AllLevels);
	long DrawTextBiDiModeFlags(long Flags);
	long DrawTextBiDiModeFlagsReadingOnly();
	long GetControlsAlignment();
	void InitiateAction();
	BOOL IsRightToLeft();
	BOOL UseRightToLeftAlignment();
	BOOL UseRightToLeftReading();
	BOOL UseRightToLeftScrollBar();
	short GetCursor();
	void SetCursor(short nNewValue);
	BOOL ClassNameIs(LPCTSTR Name);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IZSSMSX_H__92CF5024_C066_46A1_8211_2E5FF3EBF5CD__INCLUDED_)
