//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by KeepLink2.rc
//
#define IDQUIT                          2
#define IDD_ABOUTBOX                    100
#define IDD_KEEPLINK2_FORM              101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_KEEPTYPE                    129
#define IDB_LOGO                        131
#define IDI_ICON_LOGO                   133
#define IDI_ICON_PORT                   134
#define IDI_ICON_ORDI                   135
#define IDI_ICON_NAME                   136
#define IDD_NEW_RULE                    137
#define IDD_PROPRIETE                   138
#define IDD_GENERAL                     140
#define IDB_VOYANT                      140
#define IDD_ALERTE_MAIL                 141
#define IDI_ICON_SON                    141
#define IDD_ALERTE_SMS                  142
#define IDB_LOGO2                       142
#define IDD_ALERTE_SON                  143
#define IDI_ICON_MAIL                   143
#define IDD_ALERTE_SYSLOG               144
#define IDI_ICON_MAILDISABLE            144
#define IDB_SPLASH                      144
#define IDI_ICON_SONDISABLE             145
#define IDI_ICON_SYSLOG                 147
#define IDI_ICON_SYSLOGDISABLE          148
#define IDC_HAND                        149
#define IDB_PETIT_LOGO                  150
#define IDB_VBANNER                     152
#define IDI_ICON_DESKTOP                154
#define IDD_SCAN                        155
#define IDI_ICON_SEARCH                 158
#define IDD_SCAN_VIEW                   159
#define IDI_ICON_SMS                    160
#define IDI_ICON_SMSDISABLE             161
#define IDR_TRAYICON                    163
#define IDD_SEND_SMS                    164
#define IDI_ICON_MODEM                  166
#define IDB_FRAME                       167
#define IDB_LED_ALERTE                  168
#define IDI_ICON_GREEN                  177
#define IDI_ICON_RED                    178
#define IDI_ICON_INTERNET_OFF           179
#define IDI_ICON_INTERNET_ON            180
#define IDD_UPDATE                      181
#define IDR_MONDE                       182
#define IDD_ARRET                       183
#define IDI_ICON_END                    185
#define IDD_AJOUT_SIMPLE                186
#define IDD_AJOUT                       187
#define IDD_AJOUT_MULTIPLE              188
#define IDB_MENU_AJOUTER                188
#define IDB_MENU_SUPPRIMER              189
#define IDD_SCANNER                     189
#define IDB_MENU_STARTALL               190
#define IDB_MENU_STOPALL                191
#define IDB_MENU_START                  192
#define IDB_MENU_STOP                   193
#define IDB_VBANNER2                    194
#define IDB_MENU_MODIFIER               195
#define IDB_MENU_PROPRIETE              196
#define IDC_TABLEAU                     1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_NAME                   1001
#define IDC_EDIT_PANNEAU_NAME           1001
#define IDC_EDIT_ECHECSON               1001
#define IDC_EDIT_SMTP                   1001
#define IDC_EDIT_REGLE_NOM              1001
#define IDC_EDIT_SCAN_ADRESSE           1001
#define IDC_EDIT2                       1002
#define IDC_TAB                         1002
#define IDC_EDIT_ADRESSE                1002
#define IDC_EDIT_OPERATOR_NAME          1002
#define IDC_EDIT_FICHIERSON             1002
#define IDC_EDIT_DEST_ADDR              1002
#define IDC_EDIT_SERVEUR_SYSLOG         1002
#define IDC_EDIT_NUM_SMS                1002
#define IDC_EDIT_NUMERO_SMS             1002
#define IDC_EDIT_NOM1                   1002
#define IDC_EDIT_SCAN_PORT_SOURCE       1002
#define IDC_APPLIQUER                   1003
#define IDC_EDIT_PORT                   1003
#define IDC_EDIT_TIME                   1003
#define IDC_EDIT_NOM_EMETEUR            1003
#define IDC_EDIT_MESSAGE_SYSLOG         1003
#define IDC_EDIT_MESSAGE_SMS            1003
#define IDC_EDIT_NOM2                   1003
#define IDC_EDIT_MAIL_LOGIN             1003
#define IDC_QUITTER                     1004
#define IDC_EDIT_ADRESSE_EMETTEUR       1004
#define IDC_EDIT_NOM3                   1004
#define IDC_EDIT_MAIL_PASSWORD          1004
#define IDC_EDIT_NOM4                   1005
#define IDC_EDIT_NOM5                   1006
#define IDC_SPIN_TIME                   1007
#define IDC_EDIT_NOM6                   1007
#define IDC_CHECK_ALERTE                1008
#define IDC_EDIT_NOM7                   1008
#define IDC_CHECK_SONENABLE             1009
#define IDC_EDIT_NOM8                   1009
#define IDC_EDIT_NOM9                   1010
#define IDC_BUTTON_PARCOURIRSON         1011
#define IDC_EDIT_NOM10                  1011
#define IDC_SPINSON                     1013
#define IDC_STATIC_SON1                 1014
#define IDC_STATIC_SON2                 1015
#define IDC_STATIC_SON3                 1016
#define IDC_CHECK_ACTIVE_MAIL           1017
#define IDC_EDIT_SUJET                  1018
#define IDC_EDIT_MESSAGE                1019
#define IDC_ICON_SON_DISABLE            1020
#define IDC_ICON_SON_ENABLE             1021
#define IDC_ICON_MAIL_DISABLE           1022
#define IDC_ICON_MAIL_ENABLE            1023
#define IDC_STATICMAIL1                 1024
#define IDC_STATICMAIL2                 1025
#define IDC_STATICMAIL3                 1026
#define IDC_STATICMAIL4                 1027
#define IDC_STATICMAIL5                 1028
#define IDC_STATICMAIL6                 1029
#define IDC_EDIT_ECHECMAIL              1030
#define IDC_SPINMAIL                    1031
#define IDC_STATICMAIL7                 1032
#define IDC_STATICMAIL8                 1033
#define IDC_BUTTON_TEST                 1034
#define IDC_CHECK_SYSLOG                1035
#define IDC_SPIN_SYSLOG                 1036
#define IDC_COMBO_SERVICE_SYSLOG        1038
#define IDC_COMBO_LEVEL_SYSLOG          1039
#define IDC_EDIT_ECHEC_SYSLOG           1040
#define IDC_STATIC_SYSLOG1              1041
#define IDC_STATIC_SYSLOG2              1042
#define IDC_STATIC_SYSLOG3              1043
#define IDC_STATIC_SYSLOG4              1044
#define IDC_STATIC_SYSLOG5              1045
#define IDC_STATIC_SYSLOG6              1046
#define IDC_ICON_SYSLOG_ENABLE          1047
#define IDC_ICON_SYSLOG_DISABLE         1048
#define IDC_COMBO1                      1049
#define IDC_BUTTON_SCAN                 1050
#define IDC_COMBO_PORT3                 1050
#define IDC_LINK                        1051
#define IDC_COMBO_PORT2                 1051
#define IDC_STATIC_TITLE                1052
#define IDC_COMBO_PORT4                 1052
#define IDC_COMBO_PORT5                 1053
#define IDC_STATIC_RULENAME             1054
#define IDC_COMBO_PORT6                 1054
#define IDC_STATIC_SURVEILLE            1055
#define IDC_COMBO_PORT7                 1055
#define IDC_STATIC_IP                   1056
#define IDC_COMBO_PORT8                 1056
#define IDC_COMBO_PORT9                 1057
#define IDC_LIST_PORT                   1058
#define IDC_COMBO_PORT10                1058
#define IDC_CHECK_SMS                   1059
#define IDC_STATIC_SMS1                 1060
#define IDC_STATIC_SMS2                 1061
#define IDC_STATIC_SMS3                 1062
#define IDC_STATIC_SMS4                 1063
#define IDC_STATIC_SMS5                 1064
#define IDC_EDIT_ECHECSMS               1065
#define IDC_COMBO_MODEM                 1066
#define IDC_STATIC_ICON_SMS             1067
#define IDC_SPIN_SMS                    1068
#define IDC_SPINSMS                     1071
#define IDC_ICON_SMS_ENABLE             1074
#define IDC_ICON_SMSDISABLE             1075
#define IDC_IZSSMSX1                    1076
#define IDC_MATRIX                      1077
#define ID_AJOUT                        1078
#define IDC_PICTURE                     1079
#define IDC_PROGRESS1                   1080
#define IDC_STATUS                      1083
#define IDC_COMBO                       1085
#define IDC_DESCRIPTION                 1086
#define IDC_EDIT_ADRESSE1               1087
#define IDC_EDIT_ADRESSE2               1088
#define IDC_RADIO_PORT_SIMPLE           1089
#define IDC_EDIT_ADRESSE3               1089
#define IDC_RADIO_PORT_MULTIPLE         1090
#define IDC_EDIT_ADRESSE4               1090
#define IDC_BUTTON_AJOUT_PORT           1091
#define IDC_EDIT_ADRESSE5               1091
#define IDC_TAB_AJOUT                   1092
#define IDC_EDIT_ADRESSE6               1092
#define IDC_COMBO_PORT                  1093
#define IDC_EDIT_ADRESSE7               1093
#define IDC_STATIC_GB_PORT_SIMPLE       1094
#define IDC_EDIT_ADRESSE8               1094
#define IDC_STATIC_GB_PORT_MULTIPLE     1095
#define IDC_EDIT_ADRESSE9               1095
#define IDC_EDIT_AJOUT_PORT             1096
#define IDC_EDIT_ADRESSE10              1096
#define IDC_COMBO_PORT1                 1099
#define ID_SCAN_START                   1101
#define IDC_EDIT_SCAN_PORT_DEST         1103
#define IDC_EDIT_SCAN_RADIO1            1104
#define IDC_EDIT_SCAN_RADIO2            1105
#define IDC_EDIT_SCAN_MAX_THREAD        1106
#define IDC_EDIT_SCAN_LIST              1107
#define IDC_EDIT_SCAN_LTHREAD           1108
#define IDC_EDIT_SCAN_TTHREAD           1109
#define IDC_EDIT_SCAN_PROGRESS          1110
#define ID_COMBO_SCAN                   1111
#define IDC_OK                          1112
#define IDC_STATIC_QUESTION             1113
#define IDC_DESCRIPT                    1114
#define IDC_SELECTALL                   1115
#define IDC_UNSELECTALL                 1116
#define IDC_CHECK_AUTH                  1119
#define IDC_STATIC_GBAUTH               1120
#define IDC_STATIC_TAILLE               1121
#define IDC_ANNULER                     1122
#define IDC_EDIT_SOURCE_ADRESSE         1124
#define IDC_STATIC_SOURCE_ADDR          1125
#define ID_RGLES_RGLES_NOUVEAU          32772
#define ID_OUTILS_RGLEDESURVEILLANCE_EDITER 32773
#define ID_OUTILS_RGLEDESURVEILLANCE_SUPPRIMER 32774
#define ID_OUTILS_RAFRAICHISSEMENT_DFINIR 32775
#define ID_OUTILS_RAFRAICHISSEMENT      32776
#define ID_OUTILS_ALERTES_CONFIGURATION 32777
#define ID_OUTILS_ALERTES_ACTIVER       32778
#define ID_OUTILS_PROPRITS              32779
#define ID_BUTTON_START                 32780
#define ID_BUTTON_STOP                  32781
#define ID_EDITION_SLCTIONNERTOUT       32782
#define ID_EDIT_SELECTALL               32783
#define ID_RGL_ARRETER                  32789
#define ID_RGL_DEMARRER                 32790
#define ID_TRAY                         32793
#define ID_MODIF_REGLE                  32794
#define ID_STARTALL                     32797
#define ID_STOPALL                      32798
#define ID_SAVEALL                      32808
#define ID__AIDEENLIGNE                 32821
#define ID_NEWORK_INDICATOR             57638
#define IDS_AIDE                        61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
